/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core_pages;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import staff.Staff;
import staff.StaffList;
import support_pages.Add_Staff;
import utilities.StateLoader;

/**
 *
 * @author quick
 */
public class StaffPage extends javax.swing.JFrame { // implements IObserver {

    private DefaultListModel listModel;
    
    private StateLoader stateLoader = new StateLoader();
    private StaffList staffList = stateLoader.RestoreStaffList();
    
    /**
     * Creates new form Staff
     */
    public StaffPage() throws IOException, ClassNotFoundException {
        
                
        try {
        staffList = stateLoader.RestoreStaffList();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        listModel = new DefaultListModel();
        refreshListModel();
        initComponents();
    }
    
    public void refreshListModel()
    {
        listModel.clear(); 
        ArrayList<Staff> listOfStaff = staffList.GetStaffList();
        for (Staff objCurrItem : listOfStaff){        
            listModel.addElement(objCurrItem.getFirstName() + ", " + objCurrItem.getLastName());    
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblVehicle = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        tbpStaff = new javax.swing.JTabbedPane();
        pneAllStaff = new javax.swing.JPanel();
        srlAllStaff = new javax.swing.JScrollPane();
        lstAllStaff = new javax.swing.JList<>();
        btnAdd_Staff = new javax.swing.JButton();
        lblLastName = new java.awt.Label();
        lblFirstName = new java.awt.Label();
        lblTitle = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Page");
        setName("frmStaff"); // NOI18N

        pnlNavigation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        lblVehicle.setText("Vehicle");
        lblVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVehicleMouseClicked(evt);
            }
        });

        lblStaff.setText("Staff");

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStaff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstAllStaff.setModel(listModel);
        lstAllStaff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        srlAllStaff.setViewportView(lstAllStaff);

        btnAdd_Staff.setText("Add Staff");
        btnAdd_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_StaffActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name");

        lblFirstName.setText("First Name");

        lblTitle.setText("Title");

        javax.swing.GroupLayout pneAllStaffLayout = new javax.swing.GroupLayout(pneAllStaff);
        pneAllStaff.setLayout(pneAllStaffLayout);
        pneAllStaffLayout.setHorizontalGroup(
            pneAllStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srlAllStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(pneAllStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pneAllStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pneAllStaffLayout.createSequentialGroup()
                        .addGroup(pneAllStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)
                        .addComponent(btnAdd_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pneAllStaffLayout.setVerticalGroup(
            pneAllStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pneAllStaffLayout.createSequentialGroup()
                .addComponent(srlAllStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pneAllStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pneAllStaffLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAdd_Staff))
                    .addGroup(pneAllStaffLayout.createSequentialGroup()
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tbpStaff.addTab("All Staff", pneAllStaff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbpStaff)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpStaff)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        this.setVisible(false);
        Homepage objWindow = new Homepage();
        objWindow.setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVehicleMouseClicked
        this.setVisible(false);
        VehiclePage objWindow = null;
        try {
            objWindow = new VehiclePage();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(StaffPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        objWindow.setVisible(true);
    }//GEN-LAST:event_lblVehicleMouseClicked

    private void btnAdd_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_StaffActionPerformed
        Add_Staff objWindow = new Add_Staff();
        objWindow.setVisible(true);  
    }//GEN-LAST:event_btnAdd_StaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StaffPage().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(StaffPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_Staff;
    private java.awt.Label lblFirstName;
    private javax.swing.JLabel lblHome;
    private java.awt.Label lblLastName;
    private javax.swing.JLabel lblStaff;
    private java.awt.Label lblTitle;
    private javax.swing.JLabel lblVehicle;
    private javax.swing.JList<String> lstAllStaff;
    private javax.swing.JPanel pneAllStaff;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JScrollPane srlAllStaff;
    private javax.swing.JTabbedPane tbpStaff;
    // End of variables declaration//GEN-END:variables
}
