/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core_pages;

import cars.Car;
import cars.CarList;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import support_pages.Add_Vehicle;
import support_pages.Hire_Vehicle;
import utilities.StateLoader;



/**
 *
 * @author quick
 */
public class VehiclePage extends javax.swing.JFrame {

    private DefaultListModel listModel;
    
    private StateLoader stateLoader = new StateLoader();
    
    private CarList carList = stateLoader.RestoreCarList();
    /**
     * Creates new form Vehicle
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public VehiclePage()throws IOException, ClassNotFoundException  {             
        try {
        carList = stateLoader.RestoreCarList();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VehiclePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        listModel = new DefaultListModel();
        refreshListModel(); 
        
        initComponents();
    }
    
    public void refreshListModel()
    {
        listModel.clear(); 
        ArrayList<Car> listOfCars = carList.GetCarList();
        for (Car objCurrItem : listOfCars){        
            listModel.addElement(objCurrItem.getMake() + ", " + objCurrItem.getModel() + ", " + objCurrItem.getRegistration()); 
            
        }
    }
    public void showSelectedItem()
    {
        ArrayList<Car> listOfCars = carList.GetCarList();
        Car objSelectedItem =
        listOfCars.get(lstAllVehicle.getSelectedIndex());
        txtMake.setText(objSelectedItem.getMake());
        txtModel.setText(objSelectedItem.getModel());
        txtReg.setText(objSelectedItem.getRegistration());
        txtMilage.setText(Integer.toString(objSelectedItem.getMileage()));
        txtMOT.setText((objSelectedItem.getMotDate().toString()));
        txtServiceMilage.setText(Integer.toString(objSelectedItem.getNextServiceMileage()));
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblVehicle = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        tbpVehicle = new javax.swing.JTabbedPane();
        pneAllVehicle = new javax.swing.JPanel();
        srlAllVehicle = new javax.swing.JScrollPane();
        lstAllVehicle = new javax.swing.JList<>();
        pneHired = new javax.swing.JPanel();
        pneMOT = new javax.swing.JPanel();
        pneService = new javax.swing.JPanel();
        pneWorkshop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnUpdateStatus = new javax.swing.JButton();
        lblMOTDate = new java.awt.Label();
        lblServiceMilage = new java.awt.Label();
        lblVehicleMileage = new java.awt.Label();
        lblVehicleMake = new java.awt.Label();
        lblVehicleReg = new java.awt.Label();
        lblVehicleStatus = new java.awt.Label();
        lblVehicleModel = new java.awt.Label();
        cmboStatus = new javax.swing.JComboBox<>();
        txtVehicleStatus = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtReg = new javax.swing.JTextField();
        txtMilage = new javax.swing.JTextField();
        txtMOT = new javax.swing.JTextField();
        txtServiceMilage = new javax.swing.JTextField();
        btnAddNewVehicle = new javax.swing.JButton();
        btnHireCar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehicle Page");
        setName("frmStaff"); // NOI18N

        pnlNavigation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        lblVehicle.setText("Vehicle");

        lblStaff.setText("Staff");
        lblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStaffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStaff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstAllVehicle.setModel(listModel);
        lstAllVehicle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAllVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAllVehicleMouseClicked(evt);
            }
        });
        srlAllVehicle.setViewportView(lstAllVehicle);

        javax.swing.GroupLayout pneAllVehicleLayout = new javax.swing.GroupLayout(pneAllVehicle);
        pneAllVehicle.setLayout(pneAllVehicleLayout);
        pneAllVehicleLayout.setHorizontalGroup(
            pneAllVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srlAllVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        pneAllVehicleLayout.setVerticalGroup(
            pneAllVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pneAllVehicleLayout.createSequentialGroup()
                .addComponent(srlAllVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        tbpVehicle.addTab("All Vehicles", pneAllVehicle);

        javax.swing.GroupLayout pneHiredLayout = new javax.swing.GroupLayout(pneHired);
        pneHired.setLayout(pneHiredLayout);
        pneHiredLayout.setHorizontalGroup(
            pneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        pneHiredLayout.setVerticalGroup(
            pneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tbpVehicle.addTab("Hired", pneHired);

        javax.swing.GroupLayout pneMOTLayout = new javax.swing.GroupLayout(pneMOT);
        pneMOT.setLayout(pneMOTLayout);
        pneMOTLayout.setHorizontalGroup(
            pneMOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        pneMOTLayout.setVerticalGroup(
            pneMOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tbpVehicle.addTab("MOT Due", pneMOT);

        javax.swing.GroupLayout pneServiceLayout = new javax.swing.GroupLayout(pneService);
        pneService.setLayout(pneServiceLayout);
        pneServiceLayout.setHorizontalGroup(
            pneServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        pneServiceLayout.setVerticalGroup(
            pneServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tbpVehicle.addTab("Service/Repeair Due", pneService);

        javax.swing.GroupLayout pneWorkshopLayout = new javax.swing.GroupLayout(pneWorkshop);
        pneWorkshop.setLayout(pneWorkshopLayout);
        pneWorkshopLayout.setHorizontalGroup(
            pneWorkshopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        pneWorkshopLayout.setVerticalGroup(
            pneWorkshopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tbpVehicle.addTab("Workshop", pneWorkshop);

        btnUpdateStatus.setText("Update Car");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        lblMOTDate.setText("MOT Date");

        lblServiceMilage.setText("Service Mileage");

        lblVehicleMileage.setText("Mileage");

        lblVehicleMake.setText("Car Make");

        lblVehicleReg.setMinimumSize(new java.awt.Dimension(60, 20));
        lblVehicleReg.setText("Car Reg");

        lblVehicleStatus.setText("Car Status:");

        lblVehicleModel.setText("Car Model");

        cmboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hire", "Return", "Send For MOT", "Return From MOT", "Send For Service", "Return From Service", "Send For Repair", "Return From Repair" }));

        txtVehicleStatus.setEditable(false);
        txtVehicleStatus.setText("Car Status");

        txtMake.setEditable(false);
        txtMake.setText("Car Make");

        txtModel.setEditable(false);
        txtModel.setText("Car Model");

        txtReg.setEditable(false);
        txtReg.setText("Car Reg");

        txtMilage.setEditable(false);
        txtMilage.setText("Car Mileage");

        txtMOT.setEditable(false);
        txtMOT.setText("MOT Date");

        txtServiceMilage.setEditable(false);
        txtServiceMilage.setText("Service Mileage");

        btnAddNewVehicle.setText("Add New Vehicle");
        btnAddNewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewVehicleActionPerformed(evt);
            }
        });

        btnHireCar.setText("Hire Car");
        btnHireCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHireCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtReg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehicleMake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehicleModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicleReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMOT, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtMilage, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(lblVehicleMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServiceMilage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMOTDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServiceMilage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVehicleStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmboStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdateStatus)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddNewVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHireCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehicleMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicleMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMilage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMOTDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateStatus)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblVehicleReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblServiceMilage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServiceMilage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddNewVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHireCar)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbpVehicle)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbpVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        this.setVisible(false);
        Homepage objWindow = new Homepage();
        objWindow.setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffMouseClicked
        this.setVisible(false);
        StaffPage objWindow = null;
        try {
            objWindow = new StaffPage();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VehiclePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        objWindow.setVisible(true);
    }//GEN-LAST:event_lblStaffMouseClicked

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        refreshListModel();
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnAddNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewVehicleActionPerformed
        Add_Vehicle objWindow = null;
        try {
            objWindow = new Add_Vehicle();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VehiclePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        objWindow.setVisible(true);   
    }//GEN-LAST:event_btnAddNewVehicleActionPerformed

    private void lstAllVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAllVehicleMouseClicked
        if (lstAllVehicle.getModel().getSize() > 1){
            showSelectedItem();
        }
    }//GEN-LAST:event_lstAllVehicleMouseClicked

    private void btnHireCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHireCarActionPerformed
        Hire_Vehicle objWindow = new Hire_Vehicle();
        objWindow.setVisible(true); 
    }//GEN-LAST:event_btnHireCarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new VehiclePage().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(VehiclePage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewVehicle;
    private javax.swing.JButton btnHireCar;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox<String> cmboStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHome;
    private java.awt.Label lblMOTDate;
    private java.awt.Label lblServiceMilage;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblVehicle;
    private java.awt.Label lblVehicleMake;
    private java.awt.Label lblVehicleMileage;
    private java.awt.Label lblVehicleModel;
    private java.awt.Label lblVehicleReg;
    private java.awt.Label lblVehicleStatus;
    private javax.swing.JList<String> lstAllVehicle;
    private javax.swing.JPanel pneAllVehicle;
    private javax.swing.JPanel pneHired;
    private javax.swing.JPanel pneMOT;
    private javax.swing.JPanel pneService;
    private javax.swing.JPanel pneWorkshop;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JScrollPane srlAllVehicle;
    private javax.swing.JTabbedPane tbpVehicle;
    private javax.swing.JTextField txtMOT;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMilage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtReg;
    private javax.swing.JTextField txtServiceMilage;
    private javax.swing.JTextField txtVehicleStatus;
    // End of variables declaration//GEN-END:variables
}
